import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'bn' | 'te' | 'mr' | 'ta' | 'gu' | 'kn';

interface Translations {
  home: string;
  donation: string;
  request: string;
  volunteer: string;
  map: string;
  profile: string;
  notifications: string;
  acceptChat: string;
  viewDetails: string;
  getDirections: string;
  donate: string;
  addDonation: string;
  addRequest: string;
  anonymous: string;
  nearbyDonations: string;
  nearbyRequests: string;
  latestActivity: string;
  welcomeMessage: string;
  howItWorks: string;
  accountSettings: string;
  saveChanges: string;
  name: string;
  email: string;
  phone: string;
  location: string;
  language: string;
  totalDonated: string;
  notificationPrefs: string;
  privacySecurity: string;
  helpSupport: string;
  aboutApp: string;
  // Volunteer translations
  available: string;
  myDeliveries: string;
  availableDeliveries: string;
  deliveriesNeedHelp: string;
  noDeliveries: string;
  checkBackLater: string;
  deliveryDetails: string;
  pickupFrom: string;
  deliverTo: string;
  distance: string;
  estimatedTime: string;
  acceptDelivery: string;
  back: string;
  activeDeliveries: string;
  noActiveDeliveries: string;
  acceptDeliveriesToSee: string;
  accepted: string;
  inProgress: string;
  completed: string;
  navigation: string;
  call: string;
  message: string;
  startDelivery: string;
  viewMap: string;
  acceptedAt: string;
  callDonor: string;
  callRecipient: string;
}

const translations: Record<Language, Translations> = {
  en: {
    home: 'Home',
    donation: 'Donation',
    request: 'Request',
    volunteer: 'Volunteer',
    map: 'Map',
    profile: 'Profile',
    notifications: 'Notifications',
    acceptChat: 'Accept & Chat',
    viewDetails: 'View Details',
    getDirections: 'Get Directions',
    donate: 'Donate',
    addDonation: 'Add Donation',
    addRequest: 'Add Request',
    anonymous: 'Anonymous',
    nearbyDonations: 'Nearby Donations',
    nearbyRequests: 'Nearby Requests',
    latestActivity: 'Latest Activity',
    welcomeMessage: 'Share what you have, get what you need',
    howItWorks: 'How HelpMate Works',
    accountSettings: 'Account Settings',
    saveChanges: 'Save Changes',
    name: 'Name',
    email: 'Email',
    phone: 'Phone Number',
    location: 'Location',
    language: 'Language',
    totalDonated: 'Total Items Donated',
    notificationPrefs: 'Notification Preferences',
    privacySecurity: 'Privacy & Security',
    helpSupport: 'Help & Support',
    aboutApp: 'About HelpMate',
    available: 'Available',
    myDeliveries: 'My Deliveries',
    availableDeliveries: 'Available Deliveries',
    deliveriesNeedHelp: 'deliveries need your help',
    noDeliveries: 'No Deliveries Available',
    checkBackLater: 'Check back later for new delivery requests',
    deliveryDetails: 'Delivery Details',
    pickupFrom: 'Pickup From',
    deliverTo: 'Deliver To',
    distance: 'Distance',
    estimatedTime: 'Est. Time',
    acceptDelivery: 'Accept Delivery',
    back: 'Back',
    activeDeliveries: 'active deliveries',
    noActiveDeliveries: 'No Active Deliveries',
    acceptDeliveriesToSee: 'Accept deliveries to see them here',
    accepted: 'Accepted',
    inProgress: 'In Progress',
    completed: 'Completed',
    navigation: 'Navigation',
    call: 'Call',
    message: 'Message',
    startDelivery: 'Start Delivery',
    viewMap: 'View Map',
    acceptedAt: 'Accepted',
    callDonor: 'Call Donor',
    callRecipient: 'Call Recipient'
  },
  hi: {
    home: 'होम',
    donation: 'दान',
    request: 'अनुरोध',
    volunteer: 'स्वयंसेवक',
    map: 'नक्शा',
    profile: 'प्रोफ़ाइल',
    notifications: 'सूचनाएं',
    acceptChat: 'स्वीकार करें और चैट करें',
    viewDetails: 'विवरण देखें',
    getDirections: 'दिशा निर्देश',
    donate: 'दान करें',
    addDonation: 'दान जोड़ें',
    addRequest: 'अनुरोध जोड़ें',
    anonymous: 'गुमनाम',
    nearbyDonations: 'आस-पास दान',
    nearbyRequests: 'आस-पास अनुरोध',
    latestActivity: 'नवीनतम गतिविधि',
    welcomeMessage: 'जो है वह साझा करें, जो चाहिए वह प्राप्त करें',
    howItWorks: 'HelpMate कैसे काम करता है',
    accountSettings: 'खाता सेटिंग्स',
    saveChanges: 'परिवर्तन सहेजें',
    name: 'नाम',
    email: 'ईमेल',
    phone: 'फ़ोन नंबर',
    location: 'स्थान',
    language: 'भाषा',
    totalDonated: 'कुल दान की गई वस्तुएं',
    notificationPrefs: 'सूचना प्राथमिकताएं',
    privacySecurity: 'गोपनीयता और सुरक्षा',
    helpSupport: 'सहायता और समर्थन',
    aboutApp: 'HelpMate के बारे में',
    available: 'उपलब्ध',
    myDeliveries: 'मेरी डिलीवरी',
    availableDeliveries: 'उपलब्ध डिलीवरी',
    deliveriesNeedHelp: 'डिलीवरी में आपकी मदद चाहिए',
    noDeliveries: 'कोई डिलीवरी उपलब्ध नहीं',
    checkBackLater: 'नई डिलीवरी अनुरोधों के लिए बाद में जांचें',
    deliveryDetails: 'डिलीवरी विवरण',
    pickupFrom: 'से पिकअप',
    deliverTo: 'को पहुंचाएं',
    distance: 'दूरी',
    estimatedTime: 'अनुमानित समय',
    acceptDelivery: 'डिलीवरी स्वीकार करें',
    back: 'वापस',
    activeDeliveries: 'सक्रिय डिलीवरी',
    noActiveDeliveries: 'कोई सक्रिय डिलीवरी नहीं',
    acceptDeliveriesToSee: 'उन्हें यहां देखने के लिए डिलीवरी स्वीकार करें',
    accepted: 'स्वीकृत',
    inProgress: 'प्रगति में',
    completed: 'पूर्ण',
    navigation: 'नेविगेशन',
    call: 'कॉल',
    message: 'संदेश',
    startDelivery: 'डिलीवरी शुरू करें',
    viewMap: 'मानचित्र देखें',
    acceptedAt: 'स्वीकृत',
    callDonor: 'दाता को कॉल करें',
    callRecipient: 'प्राप्तकर्ता को कॉल करें'
  },
  bn: {
    home: 'হোম',
    donation: 'দান',
    request: 'অনুরোধ',
    volunteer: 'স্বেচ্ছাসেবক',
    map: 'মানচিত্র',
    profile: 'প্রোফাইল',
    notifications: 'বিজ্ঞপ্তি',
    acceptChat: 'গ্রহণ করুন এবং চ্যাট করুন',
    viewDetails: 'বিস্তারিত দেখুন',
    getDirections: 'দিকনির্দেশ',
    donate: 'দান করুন',
    addDonation: 'দান যোগ করুন',
    addRequest: 'অনুরোধ যোগ করুন',
    anonymous: 'বেনামী',
    nearbyDonations: 'কাছাকাছি দান',
    nearbyRequests: 'কাছাকাছি অনুরোধ',
    latestActivity: 'সর্বশেষ কার্যকলাপ',
    welcomeMessage: 'যা আছে শেয়ার করুন, যা প্রয়োজন তা পান',
    howItWorks: 'HelpMate কীভাবে কাজ করে',
    accountSettings: 'অ্যাকাউন্ট সেটিংস',
    saveChanges: 'পরিবর্তন সংরক্ষণ করুন',
    name: 'নাম',
    email: 'ইমেল',
    phone: 'ফোন নম্বর',
    location: 'অবস্থান',
    language: 'ভাষা',
    totalDonated: 'মোট দান করা আইটেম',
    notificationPrefs: 'বিজ্ঞপ্তি পছন্দ',
    privacySecurity: 'গোপনীয়তা এবং নিরাপত্তা',
    helpSupport: 'সাহায্য এবং সমর্থন',
    aboutApp: 'HelpMate সম্পর্কে',
    available: 'উপলব্ধ',
    myDeliveries: 'আমার ডেলিভারি',
    availableDeliveries: 'উপলব্ধ ডেলিভারি',
    deliveriesNeedHelp: 'ডেলিভারিতে আপনার সাহায্য দরকার',
    noDeliveries: 'কোন ডেলিভারি উপলব্ধ নেই',
    checkBackLater: 'নতুন ডেলিভারি অনুরোধের জন্য পরে চেক করুন',
    deliveryDetails: 'ডেলিভারি বিবরণ',
    pickupFrom: 'থেকে পিকআপ',
    deliverTo: 'এ পৌঁছান',
    distance: 'দূরত্ব',
    estimatedTime: 'আনুমানিক সময়',
    acceptDelivery: 'ডেলিভারি গ্রহণ করুন',
    back: 'ফিরে যান',
    activeDeliveries: 'সক্রিয় ডেলিভারি',
    noActiveDeliveries: 'কোন সক্রিয় ডেলিভারি নেই',
    acceptDeliveriesToSee: 'এখানে দেখতে ডেলিভারি গ্রহণ করুন',
    accepted: 'গৃহীত',
    inProgress: 'চলমান',
    completed: 'সম্পন্ন',
    navigation: 'নেভিগেশন',
    call: 'কল',
    message: 'বার্তা',
    startDelivery: 'ডেলিভারি শুরু করুন',
    viewMap: 'মানচিত্র দেখুন',
    acceptedAt: 'গৃহীত',
    callDonor: 'দাতাকে কল করুন',
    callRecipient: 'প্রাপককে কল করুন'
  },
  te: {
    home: 'హోమ్',
    donation: 'దానం',
    request: 'అభ్యర్థన',
    volunteer: 'స్వచ్చంద సేవకుడు',
    map: 'మ్యాప్',
    profile: 'ప్రొఫైల్',
    notifications: 'నోటిఫికేషన్లు',
    acceptChat: 'అంగీకరించి చాట్ చేయండి',
    viewDetails: 'వివరాలు చూడండి',
    getDirections: 'దిశలు పొందండి',
    donate: 'దానం చేయండి',
    addDonation: 'దానం జోడించండి',
    addRequest: 'అభ్యర్థన జోడించండి',
    anonymous: 'అనామక',
    nearbyDonations: 'సమీప దానాలు',
    nearbyRequests: 'సమీప అభ్యర్థనలు',
    latestActivity: 'తాజా కార్యాచరణ',
    welcomeMessage: 'మీ దగ్గర ఉన్నది పంచుకోండి, మీకు కావాల్సింది పొందండి',
    howItWorks: 'HelpMate ఎలా పనిచేస్తుంది',
    accountSettings: 'ఖాతా సెట్టింగ్‌లు',
    saveChanges: 'మార్పులను సేవ్ చేయండి',
    name: 'పేరు',
    email: 'ఇమెయిల్',
    phone: 'ఫోన్ నంబర్',
    location: 'స్థానం',
    language: 'భాష',
    totalDonated: 'మొత్తం దానం చేసిన వస్తువులు',
    notificationPrefs: 'నోటిఫికేషన్ ప్రాధాన్యతలు',
    privacySecurity: 'గోప్యత & భద్రత',
    helpSupport: 'సహాయం & మద్దతు',
    aboutApp: 'HelpMate గురించి',
    available: 'అందుబాటులో',
    myDeliveries: 'నా డెలివరీలు',
    availableDeliveries: 'అందుబాటులో ఉన్న డెలివరీలు',
    deliveriesNeedHelp: 'డెలివరీలకు మీ సహాయం అవసరం',
    noDeliveries: 'డెలివరీలు అందుబాటులో లేవు',
    checkBackLater: 'కొత్త డెలివరీ అభ్యర్థనల కోసం తర్వాత తనిఖీ చేయండి',
    deliveryDetails: 'డెలివరీ వివరాలు',
    pickupFrom: 'నుండి పికప్',
    deliverTo: 'కు పంపించండి',
    distance: 'దూరం',
    estimatedTime: 'అంచనా సమయం',
    acceptDelivery: 'డెలివరీని అంగీకరించండి',
    back: 'వెనుకకు',
    activeDeliveries: 'క్రియాశీల డెలివరీలు',
    noActiveDeliveries: 'క్రియాశీల డెలివరీలు లేవు',
    acceptDeliveriesToSee: 'వాటిని ఇక్కడ చూడటానికి డెలివరీలను అంగీకరించండి',
    accepted: 'అంగీకరించబడింది',
    inProgress: 'పురోగతిలో',
    completed: 'పూర్తయింది',
    navigation: 'నావిగేషన్',
    call: 'కాల్',
    message: 'సందేశం',
    startDelivery: 'డెలివరీ ప్రారంభించండి',
    viewMap: 'మ్యాప్ చూడండి',
    acceptedAt: 'అంగీకరించబడింది',
    callDonor: 'దాతను కాల్ చేయండి',
    callRecipient: 'స్వీకరించేవారికి కాల్ చేయండి'
  },
  mr: {
    home: 'होम',
    donation: 'देणगी',
    request: 'विनंती',
    volunteer: 'स्वयंसेवक',
    map: 'नकाशा',
    profile: 'प्रोफाईल',
    notifications: 'सूचना',
    acceptChat: 'स्वीकारा आणि चॅट करा',
    viewDetails: 'तपशील पहा',
    getDirections: 'दिशानिर्देश',
    donate: 'दान करा',
    addDonation: 'देणगी जोडा',
    addRequest: 'विनंती जोडा',
    anonymous: 'अनामिक',
    nearbyDonations: 'जवळपासच्या देणग्या',
    nearbyRequests: 'जवळपासच्या विनंत्या',
    latestActivity: 'नवीनतम क्रियाकलाप',
    welcomeMessage: 'तुमच्याकडे जे आहे ते शेअर करा, तुम्हाला जे हवे ते मिळवा',
    howItWorks: 'HelpMate कसे काम करते',
    accountSettings: 'खाते सेटिंग्ज',
    saveChanges: 'बदल जतन करा',
    name: 'नाव',
    email: 'ईमेल',
    phone: 'फोन नंबर',
    location: 'स्थान',
    language: 'भाषा',
    totalDonated: 'एकूण दान केलेल्या वस्तू',
    notificationPrefs: 'सूचना प्राधान्ये',
    privacySecurity: 'गोपनीयता आणि सुरक्षा',
    helpSupport: 'मदत आणि समर्थन',
    aboutApp: 'HelpMate बद्दल',
    available: 'उपलब्ध',
    myDeliveries: 'माझी डिलिव्हरी',
    availableDeliveries: 'उपलब्ध डिलिव्हरी',
    deliveriesNeedHelp: 'डिलिव्हरीला तुमची मदत हवी आहे',
    noDeliveries: 'कोणतीही डिलिव्हरी उपलब्ध नाही',
    checkBackLater: 'नवीन डिलिव्हरी विनंत्यांसाठी नंतर तपासा',
    deliveryDetails: 'डिलिव्हरी तपशील',
    pickupFrom: 'येथून पिकअप',
    deliverTo: 'येथे पोहोचवा',
    distance: 'अंतर',
    estimatedTime: 'अंदाजे वेळ',
    acceptDelivery: 'डिलिव्हरी स्वीकारा',
    back: 'परत',
    activeDeliveries: 'सक्रिय डिलिव्हरी',
    noActiveDeliveries: 'कोणतीही सक्रिय डिलिव्हरी नाही',
    acceptDeliveriesToSee: 'येथे पाहण्यासाठी डिलिव्हरी स्वीकारा',
    accepted: 'स्वीकारले',
    inProgress: 'प्रगतीपथावर',
    completed: 'पूर्ण झाले',
    navigation: 'नेव्हिगेशन',
    call: 'कॉल',
    message: 'संदेश',
    startDelivery: 'डिलिव्हरी सुरू करा',
    viewMap: 'नकाशा पहा',
    acceptedAt: 'स्वीकारले',
    callDonor: 'दात्याला कॉल करा',
    callRecipient: 'प्राप्तकर्त्याला कॉल करा'
  },
  ta: {
    home: 'முகப்பு',
    donation: 'நன்கொடை',
    request: 'கோரிக்கை',
    volunteer: 'தன்னார்வலர்',
    map: 'வரைபடம்',
    profile: 'சுயவிவரம்',
    notifications: 'அறிவிப்புகள்',
    acceptChat: 'ஏற்று அரட்டை',
    viewDetails: 'விவரங்களைக் காண்க',
    getDirections: 'திசைகளைப் பெறுக',
    donate: 'நன்கொடை அளி',
    addDonation: 'நன்கொடை சேர்',
    addRequest: 'கோரிக்கை சேர்',
    anonymous: 'அநாமதேய',
    nearbyDonations: 'அருகிலுள்ள நன்கொடைகள்',
    nearbyRequests: 'அருகிலுள்ள கோரிக்கைகள்',
    latestActivity: 'சமீபத்திய செயல்பாடு',
    welcomeMessage: 'உங்களிடம் உள்ளதைப் பகிருங்கள், உங்களுக்குத் தேவையானதைப் பெறுங்கள்',
    howItWorks: 'HelpMate எவ்வாறு செயல்படுகிறது',
    accountSettings: 'கணக்கு அமைப்புகள்',
    saveChanges: 'மாற்றங்களைச் சேமி',
    name: 'பெயர்',
    email: 'மின்னஞ்சல்',
    phone: 'தொலைபேசி எண்',
    location: 'இடம்',
    language: 'மொழி',
    totalDonated: 'மொத்த நன்கொடை பொருட்கள்',
    notificationPrefs: 'அறிவிப்பு விருப்பத்தேர்வுகள்',
    privacySecurity: 'தனியுரிமை மற்றும் பாதுகாப்பு',
    helpSupport: 'உதவி மற்றும் ஆதரவு',
    aboutApp: 'HelpMate பற்றி',
    available: 'கிடைக்கும்',
    myDeliveries: 'என் விநியோகங்கள்',
    availableDeliveries: 'கிடைக்கும் விநியோகங்கள்',
    deliveriesNeedHelp: 'விநியோகங்களுக்கு உங்கள் உதவி தேவை',
    noDeliveries: 'விநியோகங்கள் இல்லை',
    checkBackLater: 'புதிய விநியோக கோரிக்கைகளுக்கு பின்னர் சரிபார்க்கவும்',
    deliveryDetails: 'விநியோக விவரங்கள்',
    pickupFrom: 'இருந்து எடு',
    deliverTo: 'க்கு வழங்கு',
    distance: 'தூரம்',
    estimatedTime: 'மதிப்பிடப்பட்ட நேரம்',
    acceptDelivery: 'விநியோகத்தை ஏற்கவும்',
    back: 'பின்',
    activeDeliveries: 'செயலில் உள்ள விநியோகங்கள்',
    noActiveDeliveries: 'செயலில் உள்ள விநியோகங்கள் இல்லை',
    acceptDeliveriesToSee: 'இங்கே பார்க்க விநியோகங்களை ஏற்கவும்',
    accepted: 'ஏற்கப்பட்டது',
    inProgress: 'நடைபெறுகிறது',
    completed: 'முடிந்தது',
    navigation: 'வழிசெலுத்தல்',
    call: 'அழை',
    message: 'செய்தி',
    startDelivery: 'விநியோகத்தைத் தொடங்கு',
    viewMap: 'வரைபடத்தைக் காண்க',
    acceptedAt: 'ஏற்கப்பட்டது',
    callDonor: 'நன்கொடையாளரை அழைக்கவும்',
    callRecipient: 'பெறுநரை அழைக்கவும்'
  },
  gu: {
    home: 'હોમ',
    donation: 'દાન',
    request: 'વિનંતી',
    volunteer: 'સ્વયંસેવક',
    map: 'નકશો',
    profile: 'પ્રોફાઇલ',
    notifications: 'સૂચનાઓ',
    acceptChat: 'સ્વીકારો અને ચેટ કરો',
    viewDetails: 'વિગતો જુઓ',
    getDirections: 'દિશાનિર્દેશો',
    donate: 'દાન આપો',
    addDonation: 'દાન ઉમેરો',
    addRequest: 'વિનંતી ઉમેરો',
    anonymous: 'અનામી',
    nearbyDonations: 'નજીકના દાન',
    nearbyRequests: 'નજીકની વિનંતીઓ',
    latestActivity: 'તાજેતરની પ્રવૃત્તિ',
    welcomeMessage: 'તમારી પાસે જે છે તે શેર કરો, તમને જે જોઈએ છે તે મેળવો',
    howItWorks: 'HelpMate કેવી રીતે કામ કરે છે',
    accountSettings: 'એકાઉન્ટ સેટિંગ્સ',
    saveChanges: 'ફેરફારો સાચવો',
    name: 'નામ',
    email: 'ઈમેઇલ',
    phone: 'ફોન નંબર',
    location: 'સ્થાન',
    language: 'ભાષા',
    totalDonated: 'કુલ દાન કરેલી વસ્તુઓ',
    notificationPrefs: 'સૂચના પસંદગીઓ',
    privacySecurity: 'ગોપનીયતા અને સુરક્ષા',
    helpSupport: 'મદદ અને સપોર્ટ',
    aboutApp: 'HelpMate વિશે',
    available: 'ઉપલબ્ધ',
    myDeliveries: 'મારી ડિલિવરીઓ',
    availableDeliveries: 'ઉપલબ્ધ ડિલિવરીઓ',
    deliveriesNeedHelp: 'ડિલિવરીઓને તમારી મદદની જરૂર છે',
    noDeliveries: 'કોઈ ડિલિવરી ઉપલબ્ધ નથી',
    checkBackLater: 'નવી ડિલિવરી વિનંતીઓ માટે પછીથી તપાસો',
    deliveryDetails: 'ડિલિવરી વિગતો',
    pickupFrom: 'થી પિકઅપ',
    deliverTo: 'ને પહોંચાડો',
    distance: 'અંતર',
    estimatedTime: 'અંદાજિત સમય',
    acceptDelivery: 'ડિલિવરી સ્વીકારો',
    back: 'પાછળ',
    activeDeliveries: 'સક્રિય ડિલિવરીઓ',
    noActiveDeliveries: 'કોઈ સક્રિય ડિલિવરીઓ નથી',
    acceptDeliveriesToSee: 'તેમને અહીં જોવા માટે ડિલિવરીઓ સ્વીકારો',
    accepted: 'સ્વીકૃત',
    inProgress: 'પ્રગતિમાં',
    completed: 'પૂર્ણ',
    navigation: 'નેવિગેશન',
    call: 'કૉલ',
    message: 'સંદેશ',
    startDelivery: 'ડિલિવરી શરૂ કરો',
    viewMap: 'નકશો જુઓ',
    acceptedAt: 'સ્વીકૃત',
    callDonor: 'દાતાને કૉલ કરો',
    callRecipient: 'પ્રાપ્તકર્તાને કૉલ કરો'
  },
  kn: {
    home: 'ಮುಖಪುಟ',
    donation: 'ದಾನ',
    request: 'ವಿನಂತಿ',
    volunteer: 'ಸ್ವಯಂಸೇವಕ',
    map: 'ನಕ್ಷೆ',
    profile: 'ಪ್ರೊಫೈಲ್',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    acceptChat: 'ಸ್ವೀಕರಿಸಿ ಮತ್ತು ಚಾಟ್ ಮಾಡಿ',
    viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    getDirections: 'ನಿರ್ದೇಶನಗಳನ್ನು ಪಡೆಯಿರಿ',
    donate: 'ದಾನ ಮಾಡಿ',
    addDonation: 'ದಾನ ಸೇರಿಸಿ',
    addRequest: 'ವಿನಂತಿ ಸೇರಿಸಿ',
    anonymous: 'ಅನಾಮಧೇಯ',
    nearbyDonations: 'ಹತ್ತಿರದ ದಾನಗಳು',
    nearbyRequests: 'ಹತ್ತಿರದ ವಿನಂತಿಗಳು',
    latestActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    welcomeMessage: 'ನಿಮ್ಮ ಬಳಿ ಇರುವುದನ್ನು ಹಂಚಿಕೊಳ್ಳಿ, ನಿಮಗೆ ಬೇಕಾದುದನ್ನು ಪಡೆಯಿರಿ',
    howItWorks: 'HelpMate ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    accountSettings: 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    saveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    name: 'ಹೆಸರು',
    email: 'ಇಮೇಲ್',
    phone: 'ದೂರವಾಣಿ ಸಂಖ್ಯೆ',
    location: 'ಸ್ಥಳ',
    language: 'ಭಾಷೆ',
    totalDonated: 'ಒಟ್ಟು ದಾನ ಮಾಡಿದ ವಸ್ತುಗಳು',
    notificationPrefs: 'ಅಧಿಸೂಚನೆ ಆದ್ಯತೆಗಳು',
    privacySecurity: 'ಗೌಪ್ಯತೆ ಮತ್ತು ಭದ್ರತೆ',
    helpSupport: 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    aboutApp: 'HelpMate ಬಗ್ಗೆ',
    available: 'ಲಭ್ಯವಿದೆ',
    myDeliveries: 'ನನ್ನ ವಿತರಣೆಗಳು',
    availableDeliveries: 'ಲಭ್ಯವಿರುವ ವಿತರಣೆಗಳು',
    deliveriesNeedHelp: 'ವಿತರಣೆಗಳಿಗೆ ನಿಮ್ಮ ಸಹಾಯ ಬೇಕು',
    noDeliveries: 'ಯಾವುದೇ ವಿತರಣೆಗಳು ಲಭ್ಯವಿಲ್ಲ',
    checkBackLater: 'ಹೊಸ ವಿತರಣಾ ವಿನಂತಿಗಳಿಗಾಗಿ ನಂತರ ಪರಿಶೀಲಿಸಿ',
    deliveryDetails: 'ವಿತರಣಾ ವಿವರಗಳು',
    pickupFrom: 'ನಿಂದ ಪಿಕಪ್',
    deliverTo: 'ಗೆ ವಿತರಿಸಿ',
    distance: 'ದೂರ',
    estimatedTime: 'ಅಂದಾಜು ಸಮಯ',
    acceptDelivery: 'ವಿತರಣೆಯನ್ನು ಸ್ವೀಕರಿಸಿ',
    back: 'ಹಿಂದೆ',
    activeDeliveries: 'ಸಕ್ರಿಯ ವಿತರಣೆಗಳು',
    noActiveDeliveries: 'ಸಕ್ರಿಯ ವಿತರಣೆಗಳಿಲ್ಲ',
    acceptDeliveriesToSee: 'ಅವುಗಳನ್ನು ಇಲ್ಲಿ ನೋಡಲು ವಿತರಣೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
    accepted: 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    navigation: 'ನ್ಯಾವಿಗೇಶನ್',
    call: 'ಕರೆ',
    message: 'ಸಂದೇಶ',
    startDelivery: 'ವಿತರಣೆ ಪ್ರಾರಂಭಿಸಿ',
    viewMap: 'ನಕ್ಷೆಯನ್ನು ವೀಕ್ಷಿಸಿ',
    acceptedAt: 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    callDonor: 'ದಾನಿಗೆ ಕರೆ ಮಾಡಿ',
    callRecipient: 'ಸ್ವೀಕರಿಸುವವರಿಗೆ ಕರೆ ಮಾಡಿ'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
